### ISSUE TITLE
Units of area calculation

### ISSUE THREAD

**Issue by mmerrittsmith** [mansueto-institute/mnp-analysis#3]
What are the units on the block area? Seems like they should be km^2, just want to be sure of that. 

Same thing for building area?

**Comment by CooperNederhood** [comment]
Yes, correct. They are both currently in sq km. So the below code block, the default unit in EPSG:3395 is meters so I'm just scaling that. For reference these things tell you the default unit for a given crs: https://epsg.io/3395

block = block.to_crs("EPSG:3395")
block['block_area'] = block.area
block['block_area'] = block['block_area'] * 1e-6
